### 
https://www.perplexity.ai/search/0638400d-59de-4d83-8e38-0cb807daf590

In [1]:
import numpy as np
from numpy import ndarray

my_array:ndarray = np.arange(1000000)
my_list = list(range(1000000))

In [2]:
%time
for _ in range(10):
    #list的comprehension,list綜合表達式
    my_list = list(range(1000000))


CPU times: total: 0 ns
Wall time: 0 ns


In [3]:
%time 

for _ in range(10):
    #list的comprehension,list綜合表達式
    my_lists = [x*2 for x in my_list]

CPU times: total: 0 ns
Wall time: 0 ns


In [4]:
%time for _ in range(10): my_array2 = my_array * 2

CPU times: total: 31.2 ms
Wall time: 35.2 ms


In [6]:
#tuple,1個元素的表示法
(4, 5)
type((4,))

tuple

In [7]:
#一維陣列
np.array(range(4)).shape

(4,)

In [ ]:
### 50個學生,每個學生有5個分數,每個分數50~100
np.random.seed(42)
scores = np.random.randint(50, 101, (50,5))
scores

In [10]:
#ndarray常用的實體屬性
scores.ndim
scores.shape
scores.size
scores.dtype

dtype('int32')

基本索引[index]和分割[slicing]
ndarray[index]
ndarray[start:end:step]

In [ ]:
#2維
scores[0][4] #類似list的操作
scores[0, 4] #ndarry的slice的操作法

np.int32(57)

In [12]:
### 取得第1位學生的分數
scores [0] #shape(5,)
scores [0,:] #shape(5,0)
scores [0:1,:] #shape(1,5)

array([[88, 78, 64, 92, 57]], dtype=int32)

In [13]:
### 取得第1,2位學生的分數
scores [:2]
scores [:2,:]
scores [(0,1),:]

array([[88, 78, 64, 92, 57],
       [70, 88, 68, 72, 60]], dtype=int32)

In [14]:
### 取得第1,2,5位學生的分數
scores [(0,1,4),:]

array([[88, 78, 64, 92, 57],
       [70, 88, 68, 72, 60],
       [79, 87, 51, 70, 82]], dtype=int32)

In [15]:
### 取得第1科的所有分數
scores [:,0] #(50,)
scores [:,0:1] #(1,50)

array([[ 88],
       [ 70],
       [ 60],
       [ 52],
       [ 79],
       [ 61],
       [ 76],
       [ 96],
       [100],
       [ 67],
       [ 58],
       [ 96],
       [ 84],
       [ 89],
       [ 53],
       [ 83],
       [ 97],
       [ 89],
       [ 96],
       [ 90],
       [ 74],
       [ 93],
       [ 66],
       [ 54],
       [ 56],
       [ 82],
       [ 84],
       [ 84],
       [ 63],
       [ 63],
       [ 64],
       [ 81],
       [ 79],
       [ 64],
       [ 81],
       [ 51],
       [ 77],
       [ 60],
       [ 50],
       [ 88],
       [ 86],
       [ 73],
       [ 90],
       [ 51],
       [ 66],
       [ 72],
       [ 68],
       [ 55],
       [ 87],
       [ 71]], dtype=int32)

In [16]:
### 取得第1,2科的所有分數
scores [:,0:2] #(50,2)

array([[ 88,  78],
       [ 70,  88],
       [ 60,  73],
       [ 52,  71],
       [ 79,  87],
       [ 61,  71],
       [ 76,  91],
       [ 96, 100],
       [100,  56],
       [ 67,  53],
       [ 58,  75],
       [ 96,  56],
       [ 84,  63],
       [ 89,  53],
       [ 53,  78],
       [ 83,  59],
       [ 97,  64],
       [ 89,  70],
       [ 96,  73],
       [ 90,  78],
       [ 74,  56],
       [ 93,  57],
       [ 66,  57],
       [ 54,  91],
       [ 56,  58],
       [ 82,  97],
       [ 84,  93],
       [ 84,  50],
       [ 63,  52],
       [ 63,  88],
       [ 64,  75],
       [ 81,  88],
       [ 79,  86],
       [ 64,  92],
       [ 81,  56],
       [ 51,  91],
       [ 77,  93],
       [ 60,  77],
       [ 50,  76],
       [ 88,  55],
       [ 86,  82],
       [ 73,  64],
       [ 90,  98],
       [ 51,  52],
       [ 66,  98],
       [ 72,  86],
       [ 68,  51],
       [ 55,  81],
       [ 87,  73],
       [ 71,  60]], dtype=int32)

In [17]:
### 取得前30位學生的最後3科分數
scores [:30,-3:] #(30,3)

array([[ 64,  92,  57],
       [ 68,  72,  60],
       [ 85,  89,  73],
       [ 51,  73,  93],
       [ 51,  70,  82],
       [ 93,  74,  98],
       [ 77,  65,  64],
       [ 93,  52,  86],
       [ 70,  58,  88],
       [ 74,  63,  99],
       [ 51,  69,  77],
       [ 93,  57,  96],
       [ 66,  85,  99],
       [ 51,  55,  91],
       [ 67,  75,  93],
       [ 85,  63,  80],
       [ 57,  63,  72],
       [ 65,  94,  67],
       [ 75,  74,  94],
       [ 64,  94,  50],
       [ 58,  73,  50],
       [ 73,  60, 100],
       [ 84,  84,  82],
       [ 88,  90,  77],
       [ 57,  61,  83],
       [ 72,  73,  86],
       [ 89,  71,  76],
       [ 84,  86,  96],
       [ 50,  54,  75],
       [ 76,  58,  64]], dtype=int32)

### ndarray的統計實體方法
- sum()
- min()
- max()
- mean() 平均

In [ ]:
#每個學生的總分
scores.sum(axis=1)

array([379, 358, 380, 340, 369, 397, 373, 427, 372, 356, 330, 398, 397,
       339, 366, 370, 353, 385, 412, 376, 311, 383, 373, 400, 315, 410,
       413, 400, 294, 349, 392, 401, 419, 381, 385, 368, 411, 381, 330,
       334, 452, 372, 435, 385, 343, 371, 368, 315, 352, 375])

In [19]:
#前30位學生的平均
scores[:30].mean(axis=1)

array([75.8, 71.6, 76. , 68. , 73.8, 79.4, 74.6, 85.4, 74.4, 71.2, 66. ,
       79.6, 79.4, 67.8, 73.2, 74. , 70.6, 77. , 82.4, 75.2, 62.2, 76.6,
       74.6, 80. , 63. , 82. , 82.6, 80. , 58.8, 69.8])

In [21]:
#第1科最高的分數和最低的分數
scores [:,0].max(axis=0)
scores [:,0].min(axis=0)

np.int32(50)