### numpy的reshape()


In [1]:
import numpy as np

array = np.arange(12)
array.shape


(12,)

In [2]:
array.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
array1 = array.reshape((3,4))
array1.shape

(3, 4)

In [4]:
array1 = array.reshape((3,4))
array1.shape
array1[1,2]

np.int64(6)

In [5]:
array2 = array1.reshape((2,6))
array2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [6]:
array2 = array1.reshape((2,6))
array2[1,0]

np.int64(6)

In [7]:
array3 = array2.reshape((1,2,1,6,1))
array3

array([[[[[ 0],
          [ 1],
          [ 2],
          [ 3],
          [ 4],
          [ 5]]],


        [[[ 6],
          [ 7],
          [ 8],
          [ 9],
          [10],
          [11]]]]])

In [8]:
array3 = array2.reshape((1,2,1,6,1))
array3[0,1,0,0,0]

np.int64(6)